---
title: "Resources"
toc: true
toc-depth: 3
---


## Recommended Books:

### 1. Research Exploration

- Gerring, J., & Seawright, J. (2022). *Finding Your Social Science Project: The Research Sandbox* (1st ed.). Cambridge University Press. https://doi.org/10.1017/9781009118620  
[Details](https://doi.org/10.1017/9781009118620)


### 2. Research Methods

#### Democratization
- Coppedge, M. (2012). *Democratization and Research Methods* (1st ed.). Cambridge University Press. https://doi.org/10.1017/CBO9781139016179  
[Details](https://doi.org/10.1017/CBO9781139016179)

#### Political Science

- Johnson, J. B., Reynolds, H. T., & Mycoff, J. D. (2020). *Political science research methods* (Ninth Edition). CQ Press, an imprint of SAGE Publications, Inc.
[Details](https://us.sagepub.com/en-us/nam/political-science-research-methods/book257383)

- Baglione, L. A. (2020). *Writing a research paper in political science: A practical guide to inquiry, structure, and methods* (Fourth Edition). CQ Press, an Imprint of SAGE Publications, Inc.  
[Details](https://us.sagepub.com/en-us/nam/writing-a-research-paper-in-political-science/book249472)

- Kachuyevski, A., & Samuel, L. M. (Eds.). (2018). *Doing Qualitative Research in Politics: Integrating Theory Building and Policy Relevance.* Springer International Publishing. https://doi.org/10.1007/978-3-319-72230-6  
[Details](https://doi.org/10.1007/978-3-319-72230-6)


#### Social Sciences

- Shoemaker, P. J., Tankard, J. W., & Lasorsa, D. L. (2004). *How to build social science theories.* Sage.  
[Details](https://us.sagepub.com/en-us/nam/how-to-build-social-science-theories/book225356)


#### General

- Booth, W. C., Colomb, G. G., Williams, J. M., Bizup, J., & FitzGerald, W. T. (2016). *The Craft of Research, Fourth Edition.* University of Chicago Press. https://doi.org/10.7208/chicago/9780226239873.001.0001  
[Details](https://doi.org/10.7208/chicago/9780226239873.001.0001)


### 3. Political Data Science

- Urdinez, F., & Cruz, A. (2020). *R for Political Data Science: A Practical Guide* (1st ed.). Chapman and Hall/CRC. https://doi.org/10.1201/9781003010623  
[Details](https://doi.org/10.1201/9781003010623)


- Monogan III, J. E. (2015). *Political Analysis Using R.* Springer International Publishing. https://doi.org/10.1007/978-3-319-23446-5  
[Details](https://doi.org/10.1007/978-3-319-23446-5)
